#   Copyright 2023 Google LLC
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Create an incident and an alert in OpsGenie via API

# To create a token, don't create one under "App Settings > API key management" but
# in integrations ("Settings > Integrations")

pipeline:
  - type: processor.genericjson
  - type: processor.opsgenie
    output: opsgenie_alert
    config:
      # endpoint: https://api.eu.opsgenie.com/v2
      token: "c5.........e"
      mode: alert.create
      data:
        message: "An example alert message"
        alias: "Life is too short for no alias"
        description: Every alert needs a description
        responders:
          - id: 391a68cf-2517-4e33-a432-fc303fe415e1
            type: team
        visibleTo:
          - id: 391a68cf-2517-4e33-a432-fc303fe415e1
            type: team
        actions:
          - "Restart"
          - "AnExampleAction"
        tags:
          - "OverwriteQuietHours"
          - "Critical"
        details:
          key1: value1
          key2: value2
        entity: "An example entity"
        priority: "P1"
  - type: output.logger
    config:
      message: |
        Created alert: {{ opsgenie_alert }}
  - type: processor.opsgenie
    output: opsgenie_incident
    config:
      # endpoint: https://api.eu.opsgenie.com/v2
      token: "c5.........e"
      mode: incident.create
      data:
        message: "An example incident message"
        description: "Every incident needs a description"
        responders:
          - id: 391a68cf-2517-4e33-a432-fc303fe415e1
            type: team
        tags:
          - "Outage"
          - "Critical"
        details:
          key1: value1
          key2: value2
        priority: "P1"
        impactedServices:
          - 1366196b-96b2-4b6a-b8e0-67dded37e197
        statusPageEntry:
          title: "Houston, we have a problem!"
          detail: "We've had a main B bus undervolt."
        notifyStakeholders: false
  - type: output.logger
    config:
      message: |
        Created incident: {{ opsgenie_incident }}
