#   Copyright 2022 Google LLC
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
processors:
  - genericjson
  - { processor: shellscript, config: shellscript_json }
  - { processor: shellscript, config: shellscript_yaml }
  - { processor: shellscript, config: shellscript_csv }
  - { processor: shellscript, config: shellscript_tsv }

shellscript_json:
  output: shell_json
  command: /bin/bash
  args:
    - '-c'
    - |
      while read line 
      do 
        echo "{ \"line\": \"$line\" }"
      done
      echo $STDERR_MSG > /dev/stderr
  environment:
    STDERR_MSG: 'Standard Error'
  stdin: |+
    Hello
    World

  # Set json to true, if output is JSON (single line)
  json: true
  #
  # Set jsonMultiline to true, if output is JSON (multiline)
  jsonMultiline: true
  #
  # Set yaml to true, if output is YAML
  # yaml: true
  #
  # Set csv to true, if output is comma separated values 
  # csv: true
  #
  # Set tsv to true, if output is tab separated values
  # tsv: true
  #
  # Script is successful on either exit code 0 or 1, default 0
  exitcodes: 
    - 0
    - 1

shellscript_yaml:
  output: shell_yaml
  command: /bin/bash
  args:
    - '-c'
    - |
      while read line 
      do 
        echo $line
      done
  stdin: |
    {{ { "hello" : "world" }|yaml_encode }}
  yaml: true

shellscript_csv:
  output: shell_csv
  command: /bin/bash
  args:
    - '-c'
    - |
      echo '"Hello","World","From","CSV"'
      echo "Line,\"Break"
      echo "Here\",In,CSV"
  csv: true

shellscript_tsv:
  output: shell_tsv
  command: /bin/bash
  args:
    - '-c'
    - |
      echo -e "Hello\tWorld"
  tsv: true

outputs:
  - type: logger
    message: "JSON returned: {{ shell_json }}"
  - type: logger
    message: "YAML returned: {{ shell_yaml }}"
  - type: logger
    message: "CSV returned: {{ shell_csv }}"
  - type: logger
    message: "TSV returned: {{ shell_tsv }}"